name: Release image

on:
  push:
    branches: [ ci/init ]

jobs:
  push-image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: |
          echo "${{ github.token }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build --push \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/ghosts-network/notifications:latest .
